import type { Metadata } from "next";
import { Parkinsans } from "next/font/google";
import "./globals.css";

const parkinsans = Parkinsans({
  subsets: ["latin"],
  // weight: ["800"],
  // variable: "--font-parkinsans",
  // display: "swap",
  // adjustFontFallback: false,
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${parkinsans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
